i2cscan: avr.c File Reference
avr.c File Reference
#include <avr/io.h>
#include <util/delay.h>
#include <util/setbaud.h>
#include <stdio.h>
#include <inttypes.h>
#include <stdlib.h>
Functions
static int uart_putchar (char c, FILE *stream)
static void setup_uart ()
static void i2c_set_freq ()
static void i2c_start ()
static void i2c_stop ()
static void i2c_set_address (uint8_t addr, uint8_t rw)
static void probe_address (uint8_t i)
static void scan ()
int main ()
Variables
static FILE uart_stdout = FDEV_SETUP_STREAM(uart_putchar, NULL, _FDEV_SETUP_WRITE)
Function Documentation
i2c_set_address()
static void i2c_set_address (uint8_t addr, uint8_t rw) static
Definition at line 114 of file avr.c.
{
     // load TWI data register with the device address and read/write flag
     TWDR = (addr << 1) | rw;
     // clear TWI interrupt flag and enable TWI
     TWCR = _BV(TWINT) | _BV(TWEN);
     // wait until TWI interrupt flag is set, indicating the address is sent
     loop_until_bit_is_set(TWCR, TWINT);
 }
Referenced by probe_address().
i2c_set_freq()
static void i2c_set_freq () static
Definition at line 87 of file avr.c.
{
 #ifdef __AVR_ATmega2560__
     // for TWI (two-wire-interface) set prescaler to 1
     TWSR = 0;
     // set bit rate register for 100 kHz I2C, I2C default is 100 kHz
     TWBR = ((F_CPU / 100000UL) - 16) / 2;  // Set bit rate register
 #elif __AVR_ATmega328__
     TWBR = 32;
 #endif
 }
References F_CPU.
i2c_start()
static void i2c_start () static
Definition at line 100 of file avr.c.
{
     // stop condition on I2C bus
     TWCR = _BV(TWINT) | _BV(TWSTA) | _BV(TWEN);
     // wait until condition is complete
     loop_until_bit_is_set(TWCR, TWINT);
 }
Referenced by probe_address().
i2c_stop()
static void i2c_stop () static
Definition at line 107 of file avr.c.
{
     // stop condition on I2C bus
     TWCR = _BV(TWINT) | _BV(TWSTO) | _BV(TWEN);
     // wait until condition is complete
     loop_until_bit_is_clear(TWCR, TWSTO);
 }
Referenced by probe_address().
main()
int main (void)
Definition at line 152 of file avr.c.
            {
     // setup UART transmission
 /*    setup_uart();
     // set I2C bus frequency
     i2c_set_freq();
     for (;;)
     {
         printf("Scanning I2C bus at 100 kHz\n");
         scan();
         for (uint16_t i = 0; i < 30000; ++i)
             _delay_ms(1);
     }
     return 0;
     */
     // Set Pin 7 (Arduino Mega Pin 13) as an output
     DDRB |= (1 << PB7);
     // Initialize UART
     setup_uart();
     // Print a welcome message
     printf("UART Example: Hello, AVR!\n");
     // Main loop
     while (1) {
         // Do some processing or tasks here
         // For example, blink an LED every second
         PORTB ^= (1 << PB7);
         _delay_ms(100);      // Wait for 500 milliseconds
         printf("We're looping... wait 1000ms\n");
         _delay_ms(100);
     }
     return 0;
 }
References setup_uart().
probe_address()
static void probe_address (uint8_t i) static
Definition at line 123 of file avr.c.
{
     // flag start condition on I2C bus
     i2c_start();
 #ifdef __AVR_ATmega2560__
     // set I2C address in write mode
     i2c_set_address(i, 0);  // TW_WRITE
     // checks if address responds to ping
     if ((TWSR & 0xF8) == 0x18) {  // TW_MT_SLA_ACK
         printf("Found device at I2C address: 0x%02X (%d)\n", i, i);
     }
 #elif __AVR_ATmega328__
     i2c_set_address(i, TW_WRITE);
     if ((TWSR & TW_STATUS_MASK) == TW_MT_SLA_ACK) {
         printf("Found device at I2C address: 0x%" PRIx8 " (%" PRIu8 ")\n", i, i);
     }
 #endif
     // flag stop condition on I2C bus
     i2c_stop();
 }
References i2c_set_address(), i2c_start(), and i2c_stop().
Referenced by scan().
scan()
static void scan () static
Definition at line 146 of file avr.c.
                    {
     // for address 0-127, probe
     for (uint8_t i = 1; i < 128; ++i)
         probe_address(i);
 }
References probe_address().
setup_uart()
static void setup_uart () static
Definition at line 38 of file avr.c.
{
 #ifdef __AVR_ATmega2560__
     // disable USART during baud rate setting
     UCSR0B = 0;
 #elif __AVR_ATmega328__
     // in case UART was put into power-reduction mode ...
     PRR &= ~ _BV(PRUSART0);
 #endif
     // BAUD is defined via command line: -DBAUD=115200
     // config UART baud rate based on setbaud.h?
     //#include <util/setbaud.h>
     // UART baud HIGH BYTE
     UBRR0H = UBRRH_VALUE;
     // UART baud LOW BYTE
     UBRR0L = UBRRL_VALUE;
 #if USE_2X
     // if 2x is defined set the U2X0 bit in the UART status register A
     UCSR0A |= _BV(U2X0);
 #else
     // default to clearing the U2x0 bit
     UCSR0A &= ~_BV(U2X0);
 #endif
 #ifdef __AVR_ATmega2560__
     // set UART frame format to 8 data bits, no parity, 1 stop bit
     UCSR0C = _BV(UCSZ01) | _BV(UCSZ00);  // 8N1
     // enable UART TX and RX (transmit x recieve)
     UCSR0B = _BV(TXEN0) | _BV(RXEN0);  // Enable transmitter and receiver
 #elif __AVR_ATmega328__
     // UART Control and Status Register B:
     // - Enable transmitter only
     UCSR0B = _BV(TXEN0);
     // 8N1
     UCSR0C = _BV(UCSZ01) | _BV(UCSZ00);
 #endif
     // create redirect for stdout to UART stream
     stdout = &uart_stdout;
 }
References uart_stdout.
Referenced by main().
uart_putchar()
static int uart_putchar (char c, FILE * stream) static
Definition at line 22 of file avr.c.
{
     // if character is newline, also send carriage return
     if (c == '\n') {
         uart_putchar('\r', stream);
     }
     // wait until the UART data register is empty
     loop_until_bit_is_set(UCSR0A, UDRE0);
     // send character to UART data register
     UDR0 = c;
     return 0;
 }
Variable Documentation
uart_stdout
FILE uart_stdout = FDEV_SETUP_STREAM(uart_putchar, NULL, _FDEV_SETUP_WRITE) static
Definition at line 35 of file avr.c.
Referenced by setup_uart().