i2cscan: stm/blk/main.c File Reference
main.c File Reference
#include "stm32f4xx.h"
Functions
void delay (uint32_t ms)
int main (void)
void SystemClock_Config (void)
Function Documentation
delay()
void delay (uint32_t ms)
Definition at line 4 of file main.c.
{
     // Simple delay function
     uint32_t start = HAL_GetTick();
     while ((HAL_GetTick() - start) < ms);
 }
Referenced by main().
main()
int main (void)
Definition at line 10 of file main.c.
                {
     // Initialize HAL Library
     HAL_Init();
     // Configure system clock
     SystemClock_Config();
     // Enable GPIOC clock
     __HAL_RCC_GPIOC_CLK_ENABLE();
     // Configure PC13 as output
     GPIO_InitTypeDef GPIO_InitStruct = {0};
     GPIO_InitStruct.Pin = GPIO_PIN_13;
     GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
     GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
     HAL_GPIO_Init(GPIOC, &GPIO_InitStruct);
     // Main loop
     while (1) {
         // Toggle the LED state
         HAL_GPIO_TogglePin(GPIOC, GPIO_PIN_13);
         // Delay for a short duration
         delay(500);
     }
 }
References delay(), and SystemClock_Config().
SystemClock_Config()
void SystemClock_Config (void)
Definition at line 38 of file main.c.
{
     RCC_OscInitTypeDef RCC_OscInitStruct = {0};
     RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};
     __HAL_RCC_PWR_CLK_ENABLE();
     __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE1);
     RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSE;
     RCC_OscInitStruct.HSEState = RCC_HSE_ON;
     RCC_OscInitStruct.HSEPredivValue = RCC_HSE_PREDIV_DIV1;
     RCC_OscInitStruct.HSIState = RCC_HSI_ON;
     RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
     RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSE;
     RCC_OscInitStruct.PLL.PLLMUL = RCC_PLL_MUL9;
     if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK) {
         Error_Handler();
     }
     RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_SYSCLK | RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2;
     RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
     RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
     RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV2;
     RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;
     if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_2) != HAL_OK) {
         Error_Handler();
     }
     // Configure SysTick
     HAL_SYSTICK_Config(HAL_RCC_GetHCLKFreq() / 1000);
     HAL_SYSTICK_CLKSourceConfig(SYSTICK_CLKSOURCE_HCLK_DIV8);
     HAL_NVIC_SetPriority(SysTick_IRQn, 0, 0);
 }
Referenced by main().