i2cscan: i2cscan.h File Reference
i2cscan.h File Reference
Functions
static void bus_scan ()
static void addr_scan (const char *bus, int min, int max)
static void fetch_all ()
static void usage (const char *bin)
static void help ()
Function Documentation
addr_scan()
static void addr_scan (const char * bus, int min, int max) static
Definition at line 23 of file i2cscan.c.
{
     int file;
     // iterate through the specified I2C address range
     for (int address = min; address <= max; address++) {
         // attempt to open the I2C bus
         file = open(bus, O_RDWR);
         if (file < 0) {
             perror("Failed to open I2C bus");
             return;
         }
         // set the slave address for the current iteration
         if (ioctl(file, LINUX_I2C_SLAVE, address) < 0) {
             close(file);
             continue; // no device at this address
         }
         // attempt to read one byte from the address to check if it responds
         unsigned char buffer;
         if (read(file, &buffer, 1) == 1) {
             // device found and responded, print the address
             printf("Found device at I2C address 0x%02X\n", address);
         }
         // close the file
         close(file);
     }
 }
References LINUX_I2C_SLAVE.
Referenced by main().
bus_scan()
static void bus_scan () static
Definition at line 18 of file i2cscan.c.
                 {
     printf("SCAN FOR I2C BUSSES\n");
 }
fetch_all()
static void fetch_all () static
Definition at line 54 of file i2cscan.c.
                  {
     printf("get every I2C bus and every address on them\n");
 }
help()
static void help () static
Definition at line 127 of file i2cscan.c.
             {
     printf("\nAvailable options:\n"
             "   -h help\n"
             "   -v version\n"
             "   -l lists all available I2C busses\n"
             "   -f fetch all busses & available addresses\n"
             "   -b [BUS] specify I2C bus\n"
             "   -a scan all addresses\n"
             "   -r [FIRST-LAST] scan addresses between FIRST & LAST (int)\n"
             "   ** For MCUs **\n"
             "   -mmcu [MCU]\n"
             "   Supported MCUs :\n"
             "       - atmega328\n"
             "       - atmega2560\n"
             "       - stm32?\n"
             "\n");
 }
Referenced by main().
usage()
static void usage (const char * bin) static
Definition at line 120 of file i2cscan.c.
{
     printf("Usage: %s [-h] [-v] [-mmcu MCU] [-l] [-f] [-b] BUS [-a | -r FIRST-LAST]\n", bin);
     printf("    - BUS is an integer representing the I2C bus name\n");
     printf("    - FIRST LAST represents the MIN/MAX addresses to scan\n");
     printf("    - MCU given AVR device\n");
 }
Referenced by main().