i2cscan: stm/main.c File Reference
main.c File Reference
#include <stdint.h>
Macros
#define USART1_BASE_ADDR 0x40011000
#define RCC_BASE_ADDR 0x40023800
Functions
void delay (uint32_t count)
void uart_init (void)
void uart_send_char (char c)
void uart_send_string (const char *str)
int main (void)
Variables
volatile uint32_t *const RCC_APB2ENR = (uint32_t *)(RCC_BASE_ADDR + 0x44)
volatile uint32_t *const GPIOA_MODER = (uint32_t *)(0x40020000 + 0x00)
volatile uint32_t *const GPIOA_AFRL = (uint32_t *)(0x40020000 + 0x20)
volatile uint32_t *const USART1_SR = (uint32_t *)(USART1_BASE_ADDR + 0x00)
volatile uint32_t *const USART1_DR = (uint32_t *)(USART1_BASE_ADDR + 0x04)
volatile uint32_t *const USART1_BRR = (uint32_t *)(USART1_BASE_ADDR + 0x08)
volatile uint32_t *const USART1_CR1 = (uint32_t *)(USART1_BASE_ADDR + 0x0C)
Macro Definition Documentation
RCC_BASE_ADDR
#define RCC_BASE_ADDR 0x40023800
Definition at line 4 of file main.c.
USART1_BASE_ADDR
#define USART1_BASE_ADDR 0x40011000
Definition at line 3 of file main.c.
Function Documentation
delay()
void delay (uint32_t count)
Definition at line 14 of file main.c.
{
     for (volatile uint32_t i = 0; i < count; ++i) {
         // Delay loop
     }
 }
main()
int main (void)
Definition at line 54 of file main.c.
                {
     uart_init();
     while (1) {
         uart_send_string("Hello, UART!\r\n");
         delay(10); // Delay for a while
     }
 }
References delay(), uart_init(), and uart_send_string().
uart_init()
void uart_init (void)
Definition at line 20 of file main.c.
                      {
     // Enable GPIOA and USART1 peripheral clock
     *RCC_APB2ENR |= (1U << 0); // GPIOA
     *RCC_APB2ENR |= (1U << 4); // USART1
     // Configure PA9 (TX) as alternate function
     *GPIOA_MODER &= ~(3U << (2 * 9)); // Clear bits
     *GPIOA_MODER |= (2U << (2 * 9));  // Set as alternate function
     // Configure PA9 alternate function to USART1 TX (AF7)
     *GPIOA_AFRL &= ~(0xFU << (4 * 9)); // Clear bits
     *GPIOA_AFRL |= (7U << (4 * 9));    // Set to AF7 (USART1_TX)
     // Configure USART1
     *USART1_CR1 = 0;            // Disable USART1
     *USART1_BRR = 0x208D;       // 9600 baud rate @ 16MHz
     *USART1_CR1 |= (1U << 3);   // Enable transmitter
     *USART1_CR1 |= (1U << 13);  // Enable USART1
 }
References GPIOA_AFRL, GPIOA_MODER, RCC_APB2ENR, USART1_BRR, and USART1_CR1.
Referenced by main().
uart_send_char()
void uart_send_char (char c)
Definition at line 40 of file main.c.
{
     // Wait until the transmit data register is empty
     while (!(*USART1_SR & (1U << 7))) {}
     // Send the character
     *USART1_DR = c;
 }
References USART1_DR, and USART1_SR.
Referenced by uart_send_string().
uart_send_string()
void uart_send_string (const char * str)
Definition at line 48 of file main.c.
{
     while (*str != '\0') {
         uart_send_char(*str++);
     }
 }
References uart_send_char().
Referenced by main().
Variable Documentation
GPIOA_AFRL
volatile uint32_t* const GPIOA_AFRL = (uint32_t *)(0x40020000 + 0x20)
Definition at line 8 of file main.c.
Referenced by uart_init().
GPIOA_MODER
volatile uint32_t* const GPIOA_MODER = (uint32_t *)(0x40020000 + 0x00)
Definition at line 7 of file main.c.
Referenced by uart_init().
RCC_APB2ENR
volatile uint32_t* const RCC_APB2ENR = (uint32_t *)(RCC_BASE_ADDR + 0x44)
Definition at line 6 of file main.c.
Referenced by uart_init().
USART1_BRR
volatile uint32_t* const USART1_BRR = (uint32_t *)(USART1_BASE_ADDR + 0x08)
Definition at line 11 of file main.c.
Referenced by uart_init().
USART1_CR1
volatile uint32_t* const USART1_CR1 = (uint32_t *)(USART1_BASE_ADDR + 0x0C)
Definition at line 12 of file main.c.
Referenced by uart_init().
USART1_DR
volatile uint32_t* const USART1_DR = (uint32_t *)(USART1_BASE_ADDR + 0x04)
Definition at line 10 of file main.c.
Referenced by uart_send_char().
USART1_SR
volatile uint32_t* const USART1_SR = (uint32_t *)(USART1_BASE_ADDR + 0x00)
Definition at line 9 of file main.c.
Referenced by uart_send_char().