i2cscan: uart2.c File Reference
uart2.c File Reference
#include <avr/io.h>
#include <util/delay.h>
#include <string.h>
#include <stdio.h>
Macros
#define F_CPU 16000000UL
Functions
static int uart_putchar (char c, FILE *stream)
void USART_init ()
void USART_transmit_char (char data)
void USART_transmit_string (const char *str)
void USART_transmit_int (int value)
void USART_transmit_float (float value)
void USART_transmit_double (double value)
int main (void)
Macro Definition Documentation
F_CPU
#define F_CPU 16000000UL
Definition at line 6 of file uart2.c.
Function Documentation
main()
int main (void)
Definition at line 63 of file uart2.c.
                {
     USART_init();
     while (1) {
         const char* message = "Hello World!\n";
         USART_transmit_string(message);
         int intValue = 42;
         USART_transmit_int(intValue);
         float floatValue = 3.14;
         USART_transmit_float(floatValue);
         double doubleValue = 2.71828;
         USART_transmit_double(doubleValue);
         _delay_ms(1000); // Delay for 1 second
     }
     return 0;
 }
References USART_init(), USART_transmit_double(), USART_transmit_float(), USART_transmit_int(), and USART_transmit_string().
uart_putchar()
static int uart_putchar (char c, FILE * stream) static
Definition at line 8 of file uart2.c.
{
     if(c == '\n') { uart0_write('\r'); }
     uart0_write(c);
     return 0;
 }
USART_init()
void USART_init ()
Definition at line 14 of file uart2.c.
                   {
     // Set baud rate: 9600 baud, assuming F_CPU = 16MHz
     UBRR0H = (uint8_t)(103 >> 8);
     UBRR0L = (uint8_t)(103);
     // Enable transmitter and receiver
     UCSR0B = (1 << TXEN0) | (1 << RXEN0);
     // Set frame format: 8 data bits, 1 stop bit, no parity
     UCSR0C = (1 << UCSZ01) | (1 << UCSZ00);
 }
Referenced by main().
USART_transmit_char()
void USART_transmit_char (char data)
Definition at line 26 of file uart2.c.
{
     // Wait for empty transmit buffer
     while (!(UCSR0A & (1 << UDRE0)));
     // Put data into buffer, sends the data
     UDR0 = data;
 }
Referenced by USART_transmit_string().
USART_transmit_double()
void USART_transmit_double (double value)
Definition at line 55 of file uart2.c.
{
     char buffer[20];
     int intPart = (int)value;
     int fracPart = (int)((value - intPart) * 100);  // Two decimal places
     sprintf(buffer, "%d.%02d\n", intPart, fracPart);
     USART_transmit_string(buffer);
 }
References USART_transmit_string().
Referenced by main().
USART_transmit_float()
void USART_transmit_float (float value)
Definition at line 47 of file uart2.c.
{
     char buffer[20];
     int intPart = (int)value;
     int fracPart = (int)((value - intPart) * 100);  // Two decimal places
     sprintf(buffer, "%d.%02d\n", intPart, fracPart);
     USART_transmit_string(buffer);
 }
References USART_transmit_string().
Referenced by main().
USART_transmit_int()
void USART_transmit_int (int value)
Definition at line 41 of file uart2.c.
{
     char buffer[20];
     sprintf(buffer, "%d\n", value);
     USART_transmit_string(buffer);
 }
References USART_transmit_string().
Referenced by main().
USART_transmit_string()
void USART_transmit_string (const char * str)
Definition at line 34 of file uart2.c.
{
     // Transmit each character in the string
     for (size_t i = 0; i < strlen(str); ++i) {
         USART_transmit_char(str[i]);
     }
 }
References USART_transmit_char().
Referenced by main(), USART_transmit_double(), USART_transmit_float(), and USART_transmit_int().